### ISSUE TITLE
How can I validate an e-mail that is not the last received?

### ISSUE THREAD

**Issue by petemolinero** [WhatDaFox/Codeception-Mailtrap#15]
I have an acceptance test that generates more than one email. How can I validate all of them? This module is currently set up so that it only allows you to check the most recent e-mail received.

**Comment by foxted** [comment]
There is no support for checking older emails yet. Only the last message received.

**Comment by foxted** [comment]
@petemolinero I see you are already working on it on your fork, should I wait for your pull request or do you want me to tackle it?

**Comment by alexxvazquezz** [comment]
HI, 
I am getting this error when trying to build codecept:  [Codeception\Exception\ConfigurationException]  
  Module Mailtrap could not be found and loaded 

I enabled to module and the config in my suit.yml

class_name: SeleniumTester
modules:
    enabled:
        - Mailtrap
        - WebDriver
        - Db

```
config:
    WebDriver:
        url: 'http://localhost.com/'
        browser: 'chrome'
    Mailtrap:
        api_token: '01f3cbbd85c10e6831309495602e8124'
        inbox_id: '77268'
```

Is there anything that I am missing? Thanks
